# Generated by Django 4.2.30 on 2026-09-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bets',
            new_name='Bet',
        ),
    ]
