# Generated by Django 4.2.30 on 2026-09-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_rename_bets_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('result', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='group_name',
            new_name='coef',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='name',
            new_name='sum',
        ),
        migrations.AddField(
            model_name='bet',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.outcome'),
        ),
    ]
