# Generated by Django 4.2.30 on 2026-09-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_outcome_rename_group_name_bet_coef_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcome',
            new_name='Outcom',
        ),
    ]
