# Generated by Django 4.2.30 on 2026-09-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_rename_outcome_outcom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcom',
            new_name='Outcome',
        ),
    ]
