# Generated by Django 4.2.30 on 2026-09-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_rename_outcom_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournamet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('score_home', models.TextField()),
                ('score_away', models.TextField()),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.team')),
                ('tournamet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.tournamet')),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.event'),
        ),
    ]
