# Generated by Django 4.2.30 on 2026-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_sport_tournamet_team_event_outcome_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'Исход', 'verbose_name_plural': 'Исходы'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Спорт', 'verbose_name_plural': 'Вид спорта'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='tournamet',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
    ]
